### PR TITLE
Add silent mode

### PR DESCRIPTION
**Pull request by ellite**
Automatically add new movies or shows from a trakt list to library, via script or cron job. No need to press confirm. Ideal for headless instances of Kodi.

**Usage**:

Movies:
`kodi-send --action "RunPlugin(plugin://plugin.video.placenta/?action=moviesToLibrarySilent&url=http%3A%2F%2Fapi.trakt.tv%2Fusers%2Fme%2Flists%2Fmovie-queue%2Fitems)"`

Shows:
`kodi-send --action "RunPlugin(plugin://plugin.video.placenta/?action=tvshowsToLibrarySilent&url=http%3A%2F%2Fapi.trakt.tv%2Fusers%2Fme%2Flists%2Fshow-queue%2Fitems)"`

### CODE REVIEW

**Comment by MrBlamo420** [comment]
would you like to re look at your commit got this 
AttributeError: libmovies instance has no attribute 'silentDialog'

**Comment by ellite** [comment]
I'm on holidays. I'll have a look as soon as I have a chance.

**Comment by ellite** [comment]
Found the issue, but I'm on my phone.

On script.module.placenta/lib/resources/lib/modules/libtools.py on line 120, this should be added.

self.silentDialog = False

Forgot to initialize it. Sorry.
I should have a chance to fix it later today.

**Comment by MrBlamo420** [comment]
No worries i went ahead and fixed her up ill toss the update before i go to
bed. Was just going through stuff tonight noticed.. thanks for the help and
contributing 😊

**Comment by ellite** [comment]
It's a pleasure. Thank you.

**Comment by MrBlamo420** [comment]
Not a problem i appreciate your help

**Pull request merged**
