### PR TITLE
Updated downloader to pull from all sources

### PR DESCRIPTION
**Pull request by lashower**
I noticed that your download option only did one source at a time. Figured out how to try all sources similar to the way play works.

### CODE REVIEW

**Comment by MrBlamo420** [comment]
Thank you bud appreciate you looking at it

**Comment by MrBlamo420** [comment]
Hey dude could you re look at the merge it seems to have broke the downloader.

**Comment by lashower** [comment]
My apologies. I will double check it. I am running the code I pushed.

**Comment by lashower** [comment]
Did it give a specific error in the logs? I have a feeling some spaces were replaced with a tab or something.

**Comment by MrBlamo420** [comment]
Im not too sure man, ill click download nothing loads up ive looked at it
but i cant see anything

**Comment by lashower** [comment]
That's fine. See my latest pull request. It has a fix.

**Comment by MrBlamo420** [comment]
Okay sorry again me lol Someone messaged me. "now after starting a download
it Just keeps prompting more downloads."

**Comment by lashower** [comment]
NP. Sorry for the slow response on my part. I will double check the code. Could have sworn I included a fix that resolved that.

**Comment by lashower** [comment]
Found the problem. The return statement in downloader.py was indented twice instead of once.

**Pull request merged**
